live_config_reload = true

[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }

[colors]
draw_bold_text_with_bright_colors = true

[window]
#opacity = 0.7
dynamic_title = false
dynamic_padding = true

[window.padding]
x = 8
y = 8

[env]
WINIT_X11_SCALE_FACTOR = "1.6"
