version = 3

[transient_prompt]
  template = '; '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}green{{end}}']

[[blocks]]
    type = 'prompt'
    alignment = 'left'

    [[blocks.segments]]
    template = ' {{ .Path }} '
    foreground = '#6e8b6e'
    background = 'transparent'
    style = 'plain'
    type = 'path'

        [blocks.segments.properties]
        cache_duration = 'none'
        style = 'full'


    [[blocks.segments]]
    template = ' <#ffffff>on</> {{ .HEAD }} '
    foreground = '#ff94df'
    background = 'transparent'
    type = 'git'
    style = 'plain'

        [blocks.segments.properties]
        fetch_status = true
        branch_icon = ' <#ff94df><b> </b></>'


    [[blocks.segments]]
    style = 'plain'
    type = 'node'
    template = " <#ffffff> via</> 🌙 "


    [[blocks.segments]]
    style = 'plain'
    type = 'python'
    template = "<#ffffff>via</> 🌙 "


    [[blocks.segments]]
    style = 'plain'
    type = 'go'
    template = "<#ffffff>via</> 🌙 "


    [[blocks.segments]]
    style = 'plain'
    type = 'rust'
    template = "<#ffffff>via</> 🌙 "


    [[blocks.segments]]
    style = 'plain'
    type = 'zig'
    template = "<#ffffff>via</> 🌙 "


    [[blocks.segments]]
    style = 'plain'
    type = 'lua'
    template = "<#ffffff>via</> 🌙 "


    [[blocks.segments]]
    template = ' <#ffffff>took</> {{ .FormattedMs }} '
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'

        [blocks.segments.properties]
        treshold = 500
        style = 'round'


[[blocks]]
    type = 'prompt'
    alignment = 'left'
    newline = true

    [[blocks.segments]]
    template = '; '
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}green{{end}}']

        [blocks.segments.properties]
        cache_duration = 'none'
